/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-12-09 07:15:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import com.ox5un5h1n3.web.trendarena.util.Helper;
import java.util.List;
import com.ox5un5h1n3.web.trendarena.util.HibernateUtil;
import com.ox5un5h1n3.web.trendarena.dao.*;
import com.ox5un5h1n3.web.trendarena.entity.*;
import java.io.File;

public final class admin_005fproducts_005fbase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/Users/user/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692255386866L));
    _jspx_dependants.put("jar:file:/Users/user/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.ox5un5h1n3.web.trendarena.entity");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.ox5un5h1n3.web.trendarena.dao");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.Helper");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.HibernateUtil");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    User user = (User) session.getAttribute("userLogged");
    if (user == null) {
        response.sendRedirect(request.getContextPath()+"/login");
        return;
    } else {
        if (user.getUserType().toString().equals("USER")) {
            response.sendRedirect(request.getContextPath()+"/login");
            return;
        }
    }

      out.write('\n');
      out.write('\n');

    CategoryDao cdao = new CategoryDao(HibernateUtil.getSessionFactory());
    List<Category> list = cdao.getCategories();

    Map<String, Long> m= Helper.getCounts(HibernateUtil.getSessionFactory());

    ProductDao productDao = new ProductDao(HibernateUtil.getSessionFactory());

    List<Product> product= productDao.getAllProducts();


      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- tap on top start -->\n");
      out.write("<div class=\"tap-top\">\n");
      out.write("    <span class=\"lnr lnr-chevron-up\"></span>\n");
      out.write("</div>\n");
      out.write("<!-- tap on tap end -->\n");
      out.write("\n");
      out.write("<!-- page-wrapper Start-->\n");
      out.write("<div class=\"page-wrapper compact-wrapper\" id=\"pageWrapper\">\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_page_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Page Body Start-->\n");
      out.write("    <div class=\"page-body-wrapper\">\n");
      out.write("        <!-- Page Sidebar Start-->\n");
      out.write("        <div class=\"sidebar-wrapper\">\n");
      out.write("            <div id=\"sidebarEffect\"></div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"logo-wrapper logo-wrapper-center\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin\" data-bs-original-title=\"\" title=\"\">\n");
      out.write("                        <img class=\"img-fluid for-white\"x src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/images/logo/full-white.png\" alt=\"logo\">\n");
      out.write("                    </a>\n");
      out.write("                    <div class=\"back-btn\">\n");
      out.write("                        <i class=\"fa fa-angle-left\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"toggle-sidebar\">\n");
      out.write("                        <i class=\"ri-apps-line status_toggle middle sidebar-toggle\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"logo-icon-wrapper\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin\">\n");
      out.write("                        <img class=\"img-fluid main-logo main-white\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/images/logo/logo.png\" alt=\"logo\">\n");
      out.write("                        <img class=\"img-fluid main-logo main-dark\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/images/logo/logo-white.png\"\n");
      out.write("                             alt=\"logo\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"sidebar-main\">\n");
      out.write("                    <div class=\"left-arrow\" id=\"left-arrow\">\n");
      out.write("                        <i data-feather=\"arrow-left\"></i>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"sidebar-menu\">\n");
      out.write("                        <ul class=\"sidebar-links\" id=\"simple-bar\">\n");
      out.write("                            <li class=\"back-btn\"></li>\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"sidebar-link sidebar-title link-nav\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin\">\n");
      out.write("                                    <i class=\"ri-home-line\"></i>\n");
      out.write("                                    <span>Dashboard</span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"linear-icon-link sidebar-link sidebar-title\" href=\"javascript:void(0)\">\n");
      out.write("                                    <i class=\"ri-store-3-line\"></i>\n");
      out.write("                                    <span>Product</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sidebar-submenu\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/products\">Products</a>\n");
      out.write("                                    </li>\n");
      out.write("\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/add-new-product\">Add New Products</a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"linear-icon-link sidebar-link sidebar-title\" href=\"javascript:void(0)\">\n");
      out.write("                                    <i class=\"ri-list-check-2\"></i>\n");
      out.write("                                    <span>Category</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sidebar-submenu\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"category.html\">Category List</a>\n");
      out.write("                                    </li>\n");
      out.write("\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"add-new-category.html\">Add New Category</a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"sidebar-link sidebar-title\" href=\"javascript:void(0)\">\n");
      out.write("                                    <i class=\"ri-user-3-line\"></i>\n");
      out.write("                                    <span>Users</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sidebar-submenu\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"all-users.html\">All users</a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"add-new-user.html\">Add new user</a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"sidebar-link sidebar-title\" href=\"javascript:void(0)\">\n");
      out.write("                                    <i class=\"ri-user-3-line\"></i>\n");
      out.write("                                    <span>Roles</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sidebar-submenu\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"role.html\">All roles</a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"create-role.html\">Create Role</a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"sidebar-link sidebar-title\" href=\"javascript:void(0)\">\n");
      out.write("                                    <i class=\"ri-archive-line\"></i>\n");
      out.write("                                    <span>Orders</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sidebar-submenu\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"order-list.html\">Order List</a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"order-detail.html\">Order Detail</a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"order-tracking.html\">Order Tracking</a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"linear-icon-link sidebar-link sidebar-title\" href=\"javascript:void(0)\">\n");
      out.write("                                    <i class=\"ri-settings-line\"></i>\n");
      out.write("                                    <span>Settings</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sidebar-submenu\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"profile-setting.html\">Profile Setting</a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            <li class=\"sidebar-list\">\n");
      out.write("                                <a class=\"sidebar-link sidebar-title link-nav\" href=\"reports.html\">\n");
      out.write("                                    <i class=\"ri-file-chart-line\"></i>\n");
      out.write("                                    <span>Reports</span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                            ");
      out.write("\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"right-arrow\" id=\"right-arrow\">\n");
      out.write("                        <i data-feather=\"arrow-right\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Page Sidebar Ends-->\n");
      out.write("\n");
      out.write("        <!-- Container-fluid start-->\n");
      out.write("        <div class=\"page-body\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-12\">\n");
      out.write("                        <div class=\"card card-table\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <div class=\"title-header option-title d-sm-flex d-block\">\n");
      out.write("                                    <h5>Products List</h5>\n");
      out.write("                                    <div class=\"right-options\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a class=\"btn btn-solid\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/add-new-product\">Add Product</a>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <div>\n");
      out.write("                                    <div class=\"table-responsive\">\n");
      out.write("                                        <table class=\"table all-package theme-table table-product\" id=\"table_id\">\n");
      out.write("                                            <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th>Product Image</th>\n");
      out.write("                                                <th>Product Name</th>\n");
      out.write("                                                <th>Category</th>\n");
      out.write("\n");
      out.write("                                                <th>Price</th>\n");
      out.write("\n");
      out.write("                                                <th>Option</th>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </thead>\n");
      out.write("\n");
      out.write("                                            <tbody>\n");
      out.write("\n");
      out.write("                                            ");

                                                for (Product p : product) {

                                                    String directoryPath = request.getServletContext().getRealPath("img") + File.separator + "products";
                                            
      out.write("\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <div class=\"table-image\">\n");
      out.write("                                                        <img src=\"../img/products/");
      out.print( p.getpPhoto());
      out.write("\" class=\"img-fluid\"\n");
      out.write("                                                             alt=\"\">\n");
      out.write("                                                    </div>\n");
      out.write("                                                </td>\n");
      out.write("\n");
      out.write("                                                <td>");
      out.print( p.getpName() );
      out.write("</td>\n");
      out.write("\n");
      out.write("                                                <td>");
      out.print( p.getCategory().getCategoryTitle() );
      out.write("</td>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                                <td class=\"td-price\">$");
      out.print( p.getpPrice() );
      out.write("</td>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("                                                <td>\n");
      out.write("                                                    <ul>\n");
      out.write("                                                        <li>\n");
      out.write("                                                            <a href=\"order-detail.html\">\n");
      out.write("                                                                <i class=\"ri-eye-line\"></i>\n");
      out.write("                                                            </a>\n");
      out.write("                                                        </li>\n");
      out.write("\n");
      out.write("                                                        <li>\n");
      out.write("                                                            <a href=\"javascript:void(0)\">\n");
      out.write("                                                                <i class=\"ri-pencil-line\"></i>\n");
      out.write("                                                            </a>\n");
      out.write("                                                        </li>\n");
      out.write("\n");
      out.write("                                                        <li>\n");
      out.write("                                                            <a href=\"javascript:void(0)\" data-bs-toggle=\"modal\"\n");
      out.write("                                                               data-bs-target=\"#exampleModalToggle\">\n");
      out.write("                                                                <i class=\"ri-delete-bin-line\"></i>\n");
      out.write("                                                            </a>\n");
      out.write("                                                        </li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                            </tbody>\n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Container-fluid Ends-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- Container-fluid Ends-->\n");
      out.write("\n");
      out.write("        <!-- index body start -->\n");
      out.write("<!-- index body end -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- Page Body End -->\n");
      out.write("</div>\n");
      out.write("<!-- page-wrapper End-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_logout_modal.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- Delete Modal Box Start -->\n");
      out.write("<div class=\"modal fade theme-modal remove-coupon\" id=\"exampleModalToggle\" aria-hidden=\"true\" tabindex=\"-1\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header d-block text-center\">\n");
      out.write("                <h5 class=\"modal-title w-100\" id=\"exampleModalLabel22\">Are You Sure ?</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                    <i class=\"fas fa-times\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"remove-box\">\n");
      out.write("                    <p>The permission for the use/group, preview is inherited from the object, object will create a\n");
      out.write("                        new permission for this object</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-animation btn-md fw-bold\" data-bs-dismiss=\"modal\">No</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-animation btn-md fw-bold\" data-bs-target=\"#exampleModalToggle2\"\n");
      out.write("                        data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\">Yes</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"modal fade theme-modal remove-coupon\" id=\"exampleModalToggle2\" aria-hidden=\"true\" tabindex=\"-1\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title text-center\" id=\"exampleModalLabel12\">Done!</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                    <i class=\"fas fa-times\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"remove-box text-center\">\n");
      out.write("                    <div class=\"wrapper\">\n");
      out.write("                        <svg class=\"checkmark\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 52 52\">\n");
      out.write("                            <circle class=\"checkmark__circle\" cx=\"26\" cy=\"26\" r=\"25\" fill=\"none\" />\n");
      out.write("                            <path class=\"checkmark__check\" fill=\"none\" d=\"M14.1 27.2l7.1 7.2 16.7-16.8\" />\n");
      out.write("                        </svg>\n");
      out.write("                    </div>\n");
      out.write("                    <h4 class=\"text-content\">It's Removed.</h4>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Delete Modal Box End -->\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_script_imports.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
