/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-12-09 06:08:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.ox5un5h1n3.web.trendarena.entity.User;
import com.ox5un5h1n3.web.trendarena.entity.Category;
import com.ox5un5h1n3.web.trendarena.dao.CategoryDao;
import com.ox5un5h1n3.web.trendarena.util.HibernateUtil;
import java.util.List;
import java.util.Map;
import com.ox5un5h1n3.web.trendarena.util.Helper;

public final class add_002dnew_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.entity.Category");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.entity.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.dao.CategoryDao");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.Helper");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.HibernateUtil");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    User user = (User) session.getAttribute("userLogged");
    if (user == null) {
        response.sendRedirect(request.getContextPath() + "/login");
        return;
    } else {
        if (user.getUserType().toString().equals("USER")) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }
    }

      out.write('\n');
      out.write('\n');

    CategoryDao cdao = new CategoryDao(HibernateUtil.getSessionFactory());
    List<Category> list = cdao.getCategories();

    Map<String, Long> m= Helper.getCounts(HibernateUtil.getSessionFactory());

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- tap on top start -->\n");
      out.write("<div class=\"tap-top\">\n");
      out.write("    <span class=\"lnr lnr-chevron-up\"></span>\n");
      out.write("</div>\n");
      out.write("<!-- tap on tap end -->\n");
      out.write("\n");
      out.write("<!-- page-wrapper start -->\n");
      out.write("<div class=\"page-wrapper compact-wrapper\" id=\"pageWrapper\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_page_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Page Body start -->\n");
      out.write("    <div class=\"page-body-wrapper\">\n");
      out.write("        <!-- Page Sidebar Start-->\n");
      out.write("        <div class=\"sidebar-wrapper\">\n");
      out.write("            <div id=\"sidebarEffect\"></div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"logo-wrapper logo-wrapper-center\">\n");
      out.write("                    <a href=\"index.html\" data-bs-original-title=\"\" title=\"\">\n");
      out.write("                        <img class=\"img-fluid for-white\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/images/logo/full-white.png\"\n");
      out.write("                             alt=\"logo\">\n");
      out.write("                    </a>\n");
      out.write("                    <div class=\"back-btn\">\n");
      out.write("                        <i class=\"fa fa-angle-left\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"toggle-sidebar\">\n");
      out.write("                        <i class=\"ri-apps-line status_toggle middle sidebar-toggle\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"logo-icon-wrapper\">\n");
      out.write("                    <a href=\"index.html\">\n");
      out.write("                        <img class=\"img-fluid main-logo main-white\"\n");
      out.write("                             src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/images/logo/1-white.png\" alt=\"logo\">\n");
      out.write("                        <img class=\"img-fluid main-logo main-dark\"\n");
      out.write("                             src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/images/logo/logo-white.png\"\n");
      out.write("                             alt=\"logo\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"sidebar-main\">\n");
      out.write("                    <div class=\"left-arrow\" id=\"left-arrow\">\n");
      out.write("                        <i data-feather=\"arrow-left\"></i>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"right-arrow\" id=\"right-arrow\">\n");
      out.write("                        <i data-feather=\"arrow-right\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Page Sidebar Ends-->\n");
      out.write("\n");
      out.write("        <div class=\"page-body\">\n");
      out.write("\n");
      out.write("            <!-- New Product Add Start -->\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-12\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-sm-8 m-auto\">\n");
      out.write("                                <div class=\"card\">\n");
      out.write("                                    <div class=\"card-body\">\n");
      out.write("                                        <div class=\"card-header-2\">\n");
      out.write("                                            <h5>Product Information</h5>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <form class=\"theme-form theme-form-2 mega-form\"\n");
      out.write("                                              enctype=\"multipart/form-data\">\n");
      out.write("                                            <div class=\"mb-4 row align-items-center\">\n");
      out.write("                                                <label class=\"form-label-title col-sm-3 mb-0\">Name</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\"\n");
      out.write("                                                           placeholder=\"Product name\" name=\"pName\" id=\"pName\" required />\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"mb-4 row align-items-center\">\n");
      out.write("                                                <label class=\"col-sm-3 col-form-label form-label-title\">Description</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <textarea style=\"height: 150px;\" class=\"form-control\"\n");
      out.write("                                                              placeholder=\"Product description\" name=\"pDesc\" id=\"pDesc\" required></textarea>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"mb-4 row align-items-center\">\n");
      out.write("                                                <label class=\"col-sm-3 col-form-label form-label-title\">Price</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"number\" placeholder=\"Product Price\" name=\"pPrice\" id=\"pPrice\" required />\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"mb-4 row align-items-center\">\n");
      out.write("                                                <label class=\"col-sm-3 col-form-label form-label-title\">Discount</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input type=\"number\" class=\"form-control\"\n");
      out.write("                                                           placeholder=\"Product discount\" name=\"pDiscount\" id=\"pDiscount\" required />\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"mb-4 row align-items-center\">\n");
      out.write("                                                <label class=\"col-sm-3 col-form-label form-label-title\">Quantity</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input type=\"number\" class=\"form-control\"\n");
      out.write("                                                           placeholder=\"Product quantity\" name=\"pQuantity\" id=\"pQuantity\" required />\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                            <div class=\"mb-4 row align-items-center\">\n");
      out.write("                                                <label\n");
      out.write("                                                        class=\"col-sm-3 col-form-label form-label-title\">Category</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <select class=\"js-example-basic-single w-100\" name=\"catId\" class=\"form-control\" id=\"pCategory\">\n");
      out.write("\n");
      out.write("                                                            ");

                                                                for (Category c : list) {
                                                            
      out.write("\n");
      out.write("                                                            <option value=\"");
      out.print(c.getCategoryId());
      out.write('"');
      out.write('>');
      out.print(c.getCategoryTitle());
      out.write("</option>\n");
      out.write("                                                            ");

                                                                }
                                                            
      out.write("\n");
      out.write("                                                        </select>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"row align-items-center\">\n");
      out.write("                                                <label class=\"col-sm-3 col-form-label form-label-title\">Image</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input class=\"form-control form-choose\" type=\"file\" id=\"pPic\" name=\"pPic\" required />\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"row align-items-center\">\n");
      out.write("                                                <div class=\"mt-4 \">\n");
      out.write("                                                    <a class=\"btn btn-solid add-new-product\" type=\"submit\">Add Product</a>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                        </form>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- New Product Add End -->\n");
      out.write("\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_footer.jsp", out, false);
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- Container-fluid End -->\n");
      out.write("    </div>\n");
      out.write("    <!-- Page Body End -->\n");
      out.write("</div>\n");
      out.write("<!-- page-wrapper End -->\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_logout_modal.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        document.getElementsByClassName('add-new-product').item(0).addEventListener('click', function () {\n");
      out.write("            let pName = document.getElementById('pName').value;\n");
      out.write("            let pDesc = document.getElementById('pDesc').value;\n");
      out.write("            let pPrice = document.getElementById('pPrice').value;\n");
      out.write("            let pDiscount = document.getElementById('pDiscount').value;\n");
      out.write("            let pQuantity = document.getElementById('pQuantity').value;\n");
      out.write("            let pCategory = document.getElementById('pCategory').value;\n");
      out.write("\n");
      out.write("            let fileInput = document.getElementById('pPic');\n");
      out.write("            let pPic = fileInput.files[0];\n");
      out.write("\n");
      out.write("            let formData = new FormData();\n");
      out.write("            formData.append('pName', pName);\n");
      out.write("            formData.append('pDesc', pDesc);\n");
      out.write("            formData.append('pPrice', pPrice);\n");
      out.write("            formData.append('pDiscount', pDiscount);\n");
      out.write("            formData.append('pQuantity', pQuantity);\n");
      out.write("            formData.append('pCategory', pCategory);\n");
      out.write("            formData.append('pPic', pPic);\n");
      out.write("\n");
      out.write("            if(pName.trim() === '' ||\n");
      out.write("                pDesc.trim() === '' ||\n");
      out.write("                pCategory.trim() === '') {\n");
      out.write("                alert(\"Please fill in all fields.\");\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/add-new-product`, {\n");
      out.write("                method: 'post',\n");
      out.write("                body: formData\n");
      out.write("            })\n");
      out.write("                .then(response => response.text())\n");
      out.write("                .then((text) => {\n");
      out.write("                    if (text === \"success\") {\n");
      out.write("                        alert(\"Product Added Successfully!\");\n");
      out.write("                        document.location.reload();\n");
      out.write("                    } else {\n");
      out.write("                        alert(text);\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_script_imports.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
