/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-12-11 14:36:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import com.ox5un5h1n3.web.trendarena.util.Helper;
import java.util.List;
import com.ox5un5h1n3.web.trendarena.util.HibernateUtil;
import com.ox5un5h1n3.web.trendarena.dao.*;
import com.ox5un5h1n3.web.trendarena.entity.*;
import java.io.File;

public final class all_002dusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.ox5un5h1n3.web.trendarena.entity");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.ox5un5h1n3.web.trendarena.dao");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.Helper");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.HibernateUtil");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

  User user = (User) session.getAttribute("userLogged");
  if (user == null) {
    response.sendRedirect(request.getContextPath()+"/login");
    return;
  } else {
    if (user.getUserType().toString().equals("USER")) {
      response.sendRedirect(request.getContextPath()+"/login");
      return;
    }
  }

      out.write('\n');
      out.write('\n');

  UserDao udao = new UserDao(HibernateUtil.getSessionFactory());
  List<User> users = udao.getAllUser();


      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- tap on top start -->\n");
      out.write("<div class=\"tap-top\">\n");
      out.write("  <span class=\"lnr lnr-chevron-up\"></span>\n");
      out.write("</div>\n");
      out.write("<!-- tap on tap end -->\n");
      out.write("\n");
      out.write("<!-- page-wrapper Start-->\n");
      out.write("<div class=\"page-wrapper compact-wrapper\" id=\"pageWrapper\">\n");
      out.write("\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_page_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Page Body Start-->\n");
      out.write("  <div class=\"page-body-wrapper\">\n");
      out.write("    <!-- Page Sidebar Start-->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_sidebar.jsp", out, false);
      out.write("\n");
      out.write("    <!-- Page Sidebar Ends-->\n");
      out.write("\n");
      out.write("    <!-- Container-fluid starts-->\n");
      out.write("    <div class=\"page-body\">\n");
      out.write("      <!-- All User Table Start -->\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-sm-12\">\n");
      out.write("            <div class=\"card card-table\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <div class=\"title-header option-title\">\n");
      out.write("                  <h5>All Users</h5>\n");
      out.write("                  <form class=\"d-inline-flex\">\n");
      out.write("                    <a href=\"add-new-user.html\" class=\"align-items-center btn btn-theme d-flex\">\n");
      out.write("                      <i data-feather=\"plus\"></i>Add New\n");
      out.write("                    </a>\n");
      out.write("                  </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"table-responsive table-product\">\n");
      out.write("                  <table class=\"table all-package theme-table\" id=\"table_id\">\n");
      out.write("                    <thead>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <th>Name</th>\n");
      out.write("                      <th>User Type</th>\n");
      out.write("                      <th>Phone</th>\n");
      out.write("                      <th>Email</th>\n");
      out.write("                      <th>Option</th>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("\n");
      out.write("                    <tbody>\n");
      out.write("                    ");

                      for (User u : users) {
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                      <td>");
      out.print( u.getName() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print( u.getUserType() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print( u.getPhone() );
      out.write("</td>\n");
      out.write("                      <td>");
      out.print( u.getEmail() );
      out.write("</td>\n");
      out.write("\n");
      out.write("                      <td>\n");
      out.write("                        <ul>\n");
      out.write("\n");
      out.write("                          <li>\n");
      out.write("                            <a href=\"javascript:void(0)\">\n");
      out.write("                              <i class=\"ri-pencil-line\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </li>\n");
      out.write("\n");
      out.write("                          <li>\n");
      out.write("                            <a href=\"javascript:void(0)\" data-bs-toggle=\"modal\"\n");
      out.write("                               data-bs-target=\"#exampleModalToggle\">\n");
      out.write("                              <i class=\"ri-delete-bin-line\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </li>\n");
      out.write("                        </ul>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                      }
                    
      out.write("\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                  </table>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- All User Table Ends-->\n");
      out.write("\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_footer.jsp", out, false);
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Container-fluid end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <!-- Page Body End -->\n");
      out.write("</div>\n");
      out.write("<!-- page-wrapper End-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_logout_modal.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/admin_script_imports.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
