/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-12-23 07:17:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.ox5un5h1n3.web.trendarena.dao.ProductDao;
import com.ox5un5h1n3.web.trendarena.util.HibernateUtil;
import com.ox5un5h1n3.web.trendarena.entity.Product;
import java.util.List;
import com.ox5un5h1n3.web.trendarena.dao.CategoryDao;
import com.ox5un5h1n3.web.trendarena.entity.Category;
import com.ox5un5h1n3.web.trendarena.util.Helper;

public final class view_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.entity.Category");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.entity.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.dao.CategoryDao");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.Helper");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.util.HibernateUtil");
    _jspx_imports_classes.add("com.ox5un5h1n3.web.trendarena.dao.ProductDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");

    String cat = request.getParameter("category");

    ProductDao dao = new ProductDao(HibernateUtil.getSessionFactory());
    List<Product> list = null;

    if (cat == null || cat.trim().equals("all")) {
        list = dao.getAllProducts();
    } else {
        int cid = Integer.parseInt(cat.trim());
        list = dao.getAllProductsById(cid);
    }

    CategoryDao cdao = new CategoryDao(HibernateUtil.getSessionFactory());
    List<Category> clist = cdao.getCategories();

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/product-header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"theme-color-5 bg-gradient-color\">\n");
      out.write("\n");
      out.write("<!-- Product Left Sidebar Start -->\n");
      out.write("<section class=\"product-section\">\n");
      out.write("    <div class=\"container-fluid-lg\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-xxl-9 col-xl-8 col-lg-7 wow fadeInUp\">\n");
      out.write("                <div class=\"row g-4\">\n");
      out.write("                    <div class=\"col-xl-6 wow fadeInUp\">\n");
      out.write("                        <div class=\"product-left-box\">\n");
      out.write("                            <div class=\"row g-2\">\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <div class=\"product-main-1 no-arrow\">\n");
      out.write("                                        <div>\n");
      out.write("                                            ");

                                                Product p = (Product) request.getAttribute("product");
                                                String imagePath = application.getContextPath() + "/img/products/" + p.getpPhoto();
                                            
      out.write("\n");
      out.write("                                            <img src=\"");
      out.print( imagePath );
      out.write("\" alt=\"");
      out.print( imagePath );
      out.write("\"\n");
      out.write("                                                 style=\"width: 75%;\"/>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-xl-6 wow fadeInUp\" data-wow-delay=\"0.1s\">\n");
      out.write("                        <div class=\"right-box-contain\">\n");
      out.write("                            <h6 class=\"offer-top\">");
      out.print(p.getpDiscount());
      out.write("% Off</h6>\n");
      out.write("                            <h2 class=\"name\">");
      out.print(p.getpName());
      out.write("\n");
      out.write("                            </h2>\n");
      out.write("                            <div class=\"price-rating\">\n");
      out.write("                                <h3 class=\"theme-color price\">$");
      out.print(p.getDiscountedPrice());
      out.write("\n");
      out.write("                                    <del class=\"text-content\">$");
      out.print(p.getpPrice());
      out.write("\n");
      out.write("                                    </del>\n");
      out.write("                                    <span\n");
      out.write("                                            class=\"offer theme-color\">(");
      out.print(p.getpDiscount());
      out.write("% off)</span></h3>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"procuct-contain\">\n");
      out.write("                                <p>");
      out.print(p.getpDesc());
      out.write("\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <div class=\"note-box product-packege\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <div class=\"cart_qty qty-box product-qty\">\n");
      out.write("                                    <div class=\"input-group bg-white\">\n");
      out.write("                                        <button type=\"button\" class=\"qty-left-minus bg-white\" data-type=\"minus\"\n");
      out.write("                                                data-field=\"\">\n");
      out.write("                                            <i class=\"fa fa-minus\" aria-hidden=\"true\"></i>\n");
      out.write("                                        </button>\n");
      out.write("                                        <input class=\"form-control input-number qty-input\" type=\"text\"\n");
      out.write("                                               name=\"quantity\" value=\"1\">\n");
      out.write("                                        <button type=\"button\" class=\"qty-right-plus bg-white\" data-type=\"plus\"\n");
      out.write("                                                data-field=\"\">\n");
      out.write("                                            <i class=\"fa fa-plus\" aria-hidden=\"true\"></i>\n");
      out.write("                                        </button>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <button onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart';\"\n");
      out.write("                                        class=\"btn btn-md bg-dark cart-button text-white w-100\">Add To Cart\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"buy-box\">\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\">\n");
      out.write("                                    <i data-feather=\"heart\"></i>\n");
      out.write("                                    <span>Add To Wishlist</span>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-xxl-3 col-xl-4 col-lg-5 d-none d-lg-block wow fadeInUp\">\n");
      out.write("                <div class=\"right-sidebar-box\">\n");
      out.write("\n");
      out.write("                    <!-- Trending Product -->\n");
      out.write("                    <div class=\"pt-25\">\n");
      out.write("                        <div class=\"category-menu\">\n");
      out.write("                            <h3>Trending Products</h3>\n");
      out.write("\n");
      out.write("                            <ul class=\"product-list product-right-sidebar border-0 p-0\">\n");
      out.write("\n");
      out.write("                                ");

                                    int counter = 0;
                                    for(Product trp:list) {
                                        if (counter == 4) {
                                            break;
                                        }
                                
      out.write("\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"offer-product\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("view-product/");
      out.print( trp.getPid() );
      out.write("\" class=\"offer-image\">\n");
      out.write("                                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("img/products/");
      out.print( trp.getpPhoto());
      out.write("\"\n");
      out.write("                                                 class=\"img-fluid blur-up lazyload\" alt=\"\">\n");
      out.write("                                        </a>\n");
      out.write("\n");
      out.write("                                        <div class=\"offer-detail\">\n");
      out.write("                                            <div>\n");
      out.write("                                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("view-product/");
      out.print( trp.getPid() );
      out.write("\">\n");
      out.write("                                                    <h6 class=\"name\">");
      out.print( trp.getpName());
      out.write("</h6>\n");
      out.write("                                                </a>\n");
      out.write("                                                <span>");
      out.print( trp.getpDiscount());
      out.write("% off</span>\n");
      out.write("                                                <h6 class=\"price theme-color\">$ ");
      out.print( trp.getDiscountedPrice());
      out.write("</h6>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("\n");
      out.write("                                ");

                                        counter++;
                                    }
                                    if(list.isEmpty()) {
                                        out.println("<h3>No trending products</h3>");
                                    }

                                
      out.write("\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Banner Section -->\n");
      out.write("                    <div class=\"ratio_156 pt-25\">\n");
      out.write("                        <div class=\"home-contain\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/vegetable/banner/8.jpg\" class=\"bg-img blur-up lazyload\"\n");
      out.write("                                 alt=\"\">\n");
      out.write("                            <div class=\"home-detail p-top-left home-p-medium\">\n");
      out.write("                                <div>\n");
      out.write("                                    <h6 class=\"text-yellow home-banner\">Seafood</h6>\n");
      out.write("                                    <h3 class=\"text-uppercase fw-normal\"><span\n");
      out.write("                                            class=\"theme-color fw-bold\">Freshes</span> Products</h3>\n");
      out.write("                                    <h3 class=\"fw-light\">every hour</h3>\n");
      out.write("                                    <button onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\"\n");
      out.write("                                            class=\"btn btn-animation btn-md fw-bold mend-auto\">Shop Now <i\n");
      out.write("                                            class=\"fa-solid fa-arrow-right icon\"></i></button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- Product Left Sidebar End -->\n");
      out.write("\n");
      out.write("<!-- Releted Product Section Start -->\n");
      out.write("<section class=\"product-list-section section-b-space\">\n");
      out.write("    <div class=\"container-fluid-lg\">\n");
      out.write("        <div class=\"title\">\n");
      out.write("            <h2>Related Products</h2>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row g-sm-4 g-3\">\n");
      out.write("            <div class=\"col-xxl-12 ratio_110\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"slider-6 img-slider\">\n");
      out.write("                    ");

                        for(Product plist:list)
                        {
                    
      out.write("\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"product-box-5 wow fadeInUp\">\n");
      out.write("                            <div class=\"product-image\">\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("view-product/");
      out.print( plist.getPid() );
      out.write("\">\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("img/products/");
      out.print( plist.getpPhoto());
      out.write("\"\n");
      out.write("                                         class=\"img-fluid blur-up lazyload bg-img\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                <a href=\"\" class=\"wishlist-top\" data-bs-toggle=\"tooltip\"\n");
      out.write("                                   data-bs-placement=\"top\" title=\"Wishlist\">\n");
      out.write("                                    <i data-feather=\"bookmark\"></i>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                <ul class=\"product-option\">\n");
      out.write("                                    <li data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"View\">\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        </a><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("view-product/");
      out.print( plist.getPid() );
      out.write("\">\n");
      out.write("                                        <i data-feather=\"eye\"></i>\n");
      out.write("                                    </a>\n");
      out.write("\n");
      out.write("                                    </li>\n");
      out.write("\n");
      out.write("                                    ");
      out.write("\n");
      out.write("                                    ");
      out.write("\n");
      out.write("                                    ");
      out.write("\n");
      out.write("\n");
      out.write("                                    ");
      out.write("\n");
      out.write("                                    ");
      out.write("\n");
      out.write("\n");
      out.write("                                    <li data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Add to Cart\">\n");
      out.write("                                        <a onclick=\"add_to_cart(");
      out.print(plist.getPid() );
      out.write(',');
      out.write('\'');
      out.print(plist.getpName() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(plist.getDiscountedPrice() );
      out.write("')\">\n");
      out.write("                                            <i data-feather=\"shopping-cart\"></i>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    <li data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Wishlist\">\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\" class=\"notifi-wishlist\">\n");
      out.write("                                            <i data-feather=\"heart\"></i>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"product-detail\">\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                                    <h5 class=\"name\">");
      out.print(plist.getpName() );
      out.write("</h5>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                <h5 class=\"sold text-content\">\n");
      out.write("                                    <span class=\"theme-color price\">$");
      out.print(plist.getDiscountedPrice() );
      out.write("</span>\n");
      out.write("                                    <del>$");
      out.print(plist.getpPrice() );
      out.write("</del>\n");
      out.write("                                </h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    ");

                        }
                        if(list.isEmpty()) {
                            out.println("<h3>No Related Products</h3>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- Releted Product Section End -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Quick View Modal Box Start -->\n");
      out.write("<div class=\"modal fade theme-modal view-modal\" id=\"view\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("     aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered modal-xl modal-fullscreen-sm-down\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header p-0\">\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                    <i class=\"fa-solid fa-xmark\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"row g-sm-4 g-2\">\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                        <div class=\"slider-image\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/category/1.jpg\"\n");
      out.write("                                 class=\"img-fluid blur-up lazyload\"\n");
      out.write("                                 alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                        <div class=\"right-sidebar-modal\">\n");
      out.write("                            <h4 class=\"title-name\">Peanut Butter Bite Premium Butter Cookies 600 g</h4>\n");
      out.write("                            <h4 class=\"price\">$36.99</h4>\n");
      out.write("                            <div class=\"product-rating\">\n");
      out.write("                                <ul class=\"rating\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <i data-feather=\"star\" class=\"fill\"></i>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <i data-feather=\"star\" class=\"fill\"></i>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <i data-feather=\"star\" class=\"fill\"></i>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <i data-feather=\"star\" class=\"fill\"></i>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <i data-feather=\"star\"></i>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                                <span class=\"ms-2\">8 Reviews</span>\n");
      out.write("                                <span class=\"ms-2 text-danger\">6 sold in last 16 hours</span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"product-detail\">\n");
      out.write("                                <h4>Product Details :</h4>\n");
      out.write("                                <p>Candy canes sugar plum tart cotton candy chupa chups sugar plum chocolate I love.\n");
      out.write("                                    Caramels marshmallow icing dessert candy canes I love soufflÃ© I love toffee.\n");
      out.write("                                    Marshmallow pie sweet sweet roll sesame snaps tiramisu jelly bear claw. Bonbon\n");
      out.write("                                    muffin I love carrot cake sugar plum dessert bonbon.</p>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <ul class=\"brand-list\">\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"brand-box\">\n");
      out.write("                                        <h5>Brand Name:</h5>\n");
      out.write("                                        <h6>Black Forest</h6>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"brand-box\">\n");
      out.write("                                        <h5>Product Code:</h5>\n");
      out.write("                                        <h6>W0690034</h6>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"brand-box\">\n");
      out.write("                                        <h5>Product Type:</h5>\n");
      out.write("                                        <h6>White Cream Cake</h6>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("\n");
      out.write("                            <div class=\"select-size\">\n");
      out.write("                                <h4>Cake Size :</h4>\n");
      out.write("                                <select class=\"form-select select-form-size\">\n");
      out.write("                                    <option selected>Select Size</option>\n");
      out.write("                                    <option value=\"1.2\">1/2 KG</option>\n");
      out.write("                                    <option value=\"0\">1 KG</option>\n");
      out.write("                                    <option value=\"1.5\">1/5 KG</option>\n");
      out.write("                                    <option value=\"red\">Red Roses</option>\n");
      out.write("                                    <option value=\"pink\">With Pink Roses</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"modal-button\">\n");
      out.write("                                <button onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart';\"\n");
      out.write("                                        class=\"btn btn-md add-cart-button icon\">Add\n");
      out.write("                                    To Cart\n");
      out.write("                                </button>\n");
      out.write("                                <button onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\"\n");
      out.write("                                        class=\"btn theme-bg-color view-button icon text-white fw-bold btn-md\">\n");
      out.write("                                    View More Details\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Quick View Modal Box End -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Tap to top start -->\n");
      out.write("<div class=\"theme-option\">\n");
      out.write("    <div class=\"back-to-top\">\n");
      out.write("        <a id=\"back-to-top\" href=\"#\">\n");
      out.write("            <i class=\"fas fa-chevron-up\"></i>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Tap to top end -->\n");
      out.write("\n");
      out.write("<!-- Sticky Cart Box Start -->\n");
      out.write("<div class=\"sticky-bottom-cart\">\n");
      out.write("    <div class=\"container-fluid-lg\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"cart-content\">\n");
      out.write("                    <div class=\"product-image\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/category/1.jpg\" class=\"img-fluid blur-up lazyload\"\n");
      out.write("                             alt=\"\">\n");
      out.write("                        <div class=\"content\">\n");
      out.write("                            <h5>Creamy Chocolate Cake</h5>\n");
      out.write("                            <h6>$32.96\n");
      out.write("                                <del class=\"text-danger\">$96.00</del>\n");
      out.write("                                <span>55% off</span></h6>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"selection-section\">\n");
      out.write("                        <div class=\"form-group mb-0\">\n");
      out.write("                            <select id=\"input-state\" class=\"form-control form-select\">\n");
      out.write("                                <option selected disabled>Choose Weight...</option>\n");
      out.write("                                <option>1/2 KG</option>\n");
      out.write("                                <option>1 KG</option>\n");
      out.write("                                <option>1.5 KG</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"cart_qty qty-box product-qty m-0\">\n");
      out.write("                            <div class=\"input-group h-100\">\n");
      out.write("                                <button type=\"button\" class=\"qty-left-minus\" data-type=\"minus\" data-field=\"\">\n");
      out.write("                                    <i class=\"fa fa-minus\" aria-hidden=\"true\"></i>\n");
      out.write("                                </button>\n");
      out.write("                                <input class=\"form-control input-number qty-input\" type=\"text\" name=\"quantity\"\n");
      out.write("                                       value=\"1\">\n");
      out.write("                                <button type=\"button\" class=\"qty-right-plus\" data-type=\"plus\" data-field=\"\">\n");
      out.write("                                    <i class=\"fa fa-plus\" aria-hidden=\"true\"></i>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"add-btn\">\n");
      out.write("                        <a class=\"btn theme-bg-color text-white wishlist-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\"><i\n");
      out.write("                                class=\"fa fa-bookmark\"></i> Wishlist</a>\n");
      out.write("                        <a class=\"btn theme-bg-color text-white\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\"><i\n");
      out.write("                                class=\"fas fa-shopping-cart\"></i> Add To Cart</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- Sticky Cart Box End -->\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/other-footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bg overlay Start -->\n");
      out.write("<div class=\"bg-overlay\"></div>\n");
      out.write("<!-- Bg overlay End -->\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/script_imports.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
