/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-17 11:12:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\n");
      out.write("    <!-- Required meta tags -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <meta name=\"description\" content=\"TrendArena | Shop with ease, anytime, anywhere\">\n");
      out.write("\n");
      out.write("    <meta name=\"author\" content=\"TrendArena\">\n");
      out.write("\n");
      out.write("    <title>TrendArena. | Shop with ease, anytime, anywhere</title>\n");
      out.write("\n");
      out.write("    <!-- Favicon -->\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/favicon.png\" />\n");
      out.write("\n");
      out.write("    <!-- Themefisher Icon font -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/themefisher-font/style.css\">\n");
      out.write("    <!-- bootstrap.min css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/bootstrap/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/bootstrap-slider/bootstrap-slider.min.css\">\n");
      out.write("    <!-- Main Slider -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/slick-carousel/slick/slick.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/slick-carousel/slick/slick-theme.css\">\n");
      out.write("    <!-- toastr -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/plugins/toastr/toastr.min.css\">\n");
      out.write("\n");
      out.write("    <!-- Main Stylesheet -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/style.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-white w-100 navigation\" id=\"navbar\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <a class=\"navbar-brand font-weight-bold\" href=\"index.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/logo.png\" alt=\"Adrian.\"\n");
      out.write("                                                                            class=\"img-fluid\"></a>\n");
      out.write("\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#main-navbar\"\n");
      out.write("                    aria-controls=\"main-navbar\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div class=\"collapse navbar-collapse \" id=\"main-navbar\">\n");
      out.write("                <ul class=\"navbar-nav mx-auto\">\n");
      out.write("                    <li class=\"nav-item active\">\n");
      out.write("                        <a class=\"nav-link\" href=\"index.html\">Home </a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"about.html\">About Us</a>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- Pages -->\n");
      out.write("                    <li class=\"nav-item dropdown dropdown-slide\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown4\" role=\"button\" data-delay=\"350\"\n");
      out.write("                           data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                            Pages.\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown4\">\n");
      out.write("                            <li><a href=\"about.html\">About Us</a></li>\n");
      out.write("                            <li><a href=\"blog.html\">Blog</a></li>\n");
      out.write("                            <li><a href=\"blog-single.html\">Blog Single</a></li>\n");
      out.write("                            <li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("                            <li><a href=\"404.html\">404 Page</a></li>\n");
      out.write("                            <li><a href=\"faq.html\">FAQ</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li><!-- /Pages -->\n");
      out.write("                    <!-- / Blog -->\n");
      out.write("\n");
      out.write("                    <li class=\"nav-item dropdown dropdown-slide\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown3\" role=\"button\" data-delay=\"350\"\n");
      out.write("                           data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                            Shop.\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown3\">\n");
      out.write("                            <li><a href=\"shop-sidebar.html\">Shop</a></li>\n");
      out.write("                            <li><a href=\"product-single.html\">Product Details</a></li>\n");
      out.write("                            <li><a href=\"checkout.html\">Checkout</a></li>\n");
      out.write("                            <li><a href=\"favorite.html\">Favorite</a></li>\n");
      out.write("                            <li><a href=\"cart.html\">Cart</a></li>\n");
      out.write("                            <li><a href=\"empty-cart.html\">Empty Cart</a></li>\n");
      out.write("                            <li><a href=\"confirmation.html\">Confirmation</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li><!-- / Blog -->\n");
      out.write("\n");
      out.write("                    <!-- Account -->\n");
      out.write("                    <li class=\"nav-item dropdown dropdown-slide\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown5\" role=\"button\" data-delay=\"350\"\n");
      out.write("                           data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                            Account.\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown5\">\n");
      out.write("                            <li><a href=\"dashboard.html\">Dahsboard</a></li>\n");
      out.write("                            <li><a href=\"order.html\">Orders</a></li>\n");
      out.write("                            <li><a href=\"download.html\">Downloads</a></li>\n");
      out.write("                            <li><a href=\"address.html\">Address</a></li>\n");
      out.write("                            <li><a href=\"account.html\">Profile Details</a></li>\n");
      out.write("                            <li><a href=\"login.html\">Login Page</a></li>\n");
      out.write("                            <li><a href=\"signup.html\">SignUp Page</a></li>\n");
      out.write("                            <li><a href=\"forgot-password.html\">Forgot Password</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li><!-- / Account -->\n");
      out.write("\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"contact.html\">Contact Us</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- Navbar-collapse -->\n");
      out.write("\n");
      out.write("            <ul class=\"top-menu list-inline mb-0 d-none d-lg-block\" id=\"top-menu\">\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a href=\"#\" class=\"search_toggle\" id=\"search-icon\"><i class=\"tf-ion-android-search\"></i></a>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li class=\"dropdown cart-nav dropdown-slide list-inline-item\">\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle cart-icon\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\n");
      out.write("                        <i class=\"tf-ion-android-cart\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <div class=\"dropdown-menu cart-dropdown\">\n");
      out.write("\n");
      out.write("                        <!-- Cart Item -->\n");
      out.write("                        <div class=\"media\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img class=\"media-object img- mr-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/shop/cart/cart-1.jpg\" alt=\"image\" />\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"media-body\">\n");
      out.write("                                <h6>Ladies Bag</h6>\n");
      out.write("                                <div class=\"cart-price\">\n");
      out.write("                                    <span>1 x</span>\n");
      out.write("                                    <span>1250.00</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <button class=\"remove\"><i class=\"tf-ion-close\"></i></button>\n");
      out.write("                        </div><!-- / Cart Item -->\n");
      out.write("\n");
      out.write("                        <!-- Cart Item -->\n");
      out.write("                        <div class=\"media\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img class=\"media-object img-fluid mr-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/shop/cart/cart-2.jpg\" alt=\"image\" />\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"media-body\">\n");
      out.write("                                <h6>Skinny Jeans</h6>\n");
      out.write("                                <div class=\"cart-price\">\n");
      out.write("                                    <span>1 x</span>\n");
      out.write("                                    <span>1250.00</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <button class=\"remove\"><i class=\"tf-ion-close\"></i></button>\n");
      out.write("                        </div><!-- / Cart Item -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- restore delete item -->\n");
      out.write("                        <div class=\"border-bottom pb-2 mb-2\">\n");
      out.write("                            <span>Downshifter 10-4 has been deleted.</span> <button class=\"btn-inline\">Undo</button>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- /restore delete item -->\n");
      out.write("\n");
      out.write("                        <div class=\"cart-summary\">\n");
      out.write("                            <span class=\"h6\">Total</span>\n");
      out.write("                            <span class=\"total-price h6\">$1799.00</span>\n");
      out.write("\n");
      out.write("                            <div class=\"text-center cart-buttons mt-3\">\n");
      out.write("                                <a href=\"cart.html\" class=\"btn btn-small btn-transparent btn-block\">View Cart</a>\n");
      out.write("                                <a href=\"checkout.html\" class=\"btn btn-small btn-main btn-block\">Checkout</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\"><a href=\"#\"><i class=\"tf-ion-ios-person mr-3\"></i></a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!--search overlay start-->\n");
      out.write("    <div class=\"search-wrap\">\n");
      out.write("        <div class=\"overlay\">\n");
      out.write("            <form action=\"#\" class=\"search-form\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-10 col-9\">\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\" />\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-2 col-3 text-right\">\n");
      out.write("                            <div class=\"search_toggle toggle-wrap d-inline-block\">\n");
      out.write("                                <img class=\"search-close\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/close.png\" alt=\"\" />\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--search overlay end-->\n");
      out.write("\n");
      out.write("</head>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
