/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-11-30 12:46:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"TrendArena\">\n");
      out.write("    <meta name=\"keywords\" content=\"TrendArena\">\n");
      out.write("    <meta name=\"author\" content=\"TrendArena\">\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/favicon/favicon.png\" type=\"image/x-icon\">\n");
      out.write("    <title>TrendArena. | Shop with ease, anytime, anywhere</title>\n");
      out.write("\n");
      out.write("    <!-- Google font -->\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Russo+One&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pacifico&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500;600;700;800;900&display=swap\"\n");
      out.write("          rel=\"stylesheet\">\n");
      out.write("    <link\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\n");
      out.write("            rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Great+Vibes&family=Qwitcher+Grypen:wght@400;700&display=swap\"\n");
      out.write("          rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- bootstrap css -->\n");
      out.write("    <link id=\"rtl-link\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendors/bootstrap.css\">\n");
      out.write("\n");
      out.write("    <!-- wow css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/animate.min.css\" />\n");
      out.write("\n");
      out.write("    <!-- font-awesome css -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendors/font-awesome.css\">\n");
      out.write("\n");
      out.write("    <!-- feather icon css -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendors/feather-icon.css\">\n");
      out.write("\n");
      out.write("    <!-- slick css -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendors/slick/slick.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendors/slick/slick-theme.css\">\n");
      out.write("\n");
      out.write("    <!-- Iconly css -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/bulk-style.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendors/animate.css\">\n");
      out.write("\n");
      out.write("    <!-- Template css -->\n");
      out.write("    <link id=\"color-link\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/style.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Header Start -->\n");
      out.write("<header class=\"\">\n");
      out.write("    <div class=\"header-top\">\n");
      out.write("        <div class=\"container-fluid-lg\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xxl-3 d-xxl-block d-none\">\n");
      out.write("                    <div class=\"top-left-header\">\n");
      out.write("                        <i class=\"iconly-Location icli text-white\"></i>\n");
      out.write("                        <span class=\"text-white\">8717 Area 51, NV 89070, US</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-xxl-6 col-lg-9 d-lg-block d-none\">\n");
      out.write("                    <div class=\"header-offer\">\n");
      out.write("                        <div class=\"notification-slider\">\n");
      out.write("                            <div>\n");
      out.write("                                <div class=\"timer-notification\">\n");
      out.write("                                    <h6><strong class=\"me-1\">Welcome to TrendArena!</strong>Wrap new offers/gift\n");
      out.write("                                        every signle day on Weekends.<strong class=\"ms-1\">New Coupon Code: Fast024\n");
      out.write("                                        </strong>\n");
      out.write("\n");
      out.write("                                    </h6>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <div class=\"timer-notification\">\n");
      out.write("                                    <h6>Something you love is now on sale!\n");
      out.write("                                        <a href=\"shop-left-sidebar.html\" class=\"text-white\">Buy Now\n");
      out.write("                                            !</a>\n");
      out.write("                                    </h6>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"top-nav top-header sticky-header\">\n");
      out.write("        <div class=\"container-fluid-lg\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                    <div class=\"navbar-top\">\n");
      out.write("                        <button class=\"navbar-toggler d-xl-none d-inline navbar-menu-button\" type=\"button\"\n");
      out.write("                                data-bs-toggle=\"offcanvas\" data-bs-target=\"#primaryMenu\">\n");
      out.write("                                <span class=\"navbar-toggler-icon\">\n");
      out.write("                                    <i class=\"fa-solid fa-bars\"></i>\n");
      out.write("                                </span>\n");
      out.write("                        </button>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"web-logo nav-logo\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/logo/logo.png\" class=\"img-fluid blur-up lazyload\" alt=\"\">\n");
      out.write("                        </a>\n");
      out.write("\n");
      out.write("                        <div class=\"header-nav-middle\">\n");
      out.write("                            <div class=\"main-nav navbar navbar-expand-xl navbar-light navbar-sticky\">\n");
      out.write("                                <div class=\"offcanvas offcanvas-collapse order-xl-2\" id=\"primaryMenu\">\n");
      out.write("                                    <div class=\"offcanvas-header navbar-shadow\">\n");
      out.write("                                        <h5>Menu</h5>\n");
      out.write("                                        <button class=\"btn-close lead\" type=\"button\" data-bs-dismiss=\"offcanvas\"\n");
      out.write("                                                aria-label=\"Close\"></button>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"offcanvas-body\">\n");
      out.write("                                        <ul class=\"navbar-nav\">\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("                                            <li class=\"nav-item dropdown\">\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0)\"\n");
      out.write("                                                   data-bs-toggle=\"dropdown\">Product</a>\n");
      out.write("\n");
      out.write("                                                <ul class=\"dropdown-menu\">\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <a class=\"dropdown-item\" href=\"product-4-image.html\">Product\n");
      out.write("                                                            4 Image</a>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li class=\"sub-dropdown-hover\">\n");
      out.write("                                                        <a href=\"javascript:void(0)\" class=\"dropdown-item\">Product\n");
      out.write("                                                            Thumbnail</a>\n");
      out.write("                                                        <ul class=\"sub-menu\">\n");
      out.write("                                                            <li>\n");
      out.write("                                                                <a href=\"product-left-thumbnail.html\">Left\n");
      out.write("                                                                    Thumbnail</a>\n");
      out.write("                                                            </li>\n");
      out.write("\n");
      out.write("                                                            <li>\n");
      out.write("                                                                <a href=\"product-right-thumbnail.html\">Right\n");
      out.write("                                                                    Thumbnail</a>\n");
      out.write("                                                            </li>\n");
      out.write("\n");
      out.write("                                                            <li>\n");
      out.write("                                                                <a href=\"product-bottom-thumbnail.html\">Bottom\n");
      out.write("                                                                    Thumbnail</a>\n");
      out.write("                                                            </li>\n");
      out.write("                                                        </ul>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <a href=\"product-bundle.html\" class=\"dropdown-item\">Product\n");
      out.write("                                                            Bundle</a>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <a href=\"product-slider.html\" class=\"dropdown-item\">Product\n");
      out.write("                                                            Slider</a>\n");
      out.write("                                                    </li>\n");
      out.write("                                                    <li>\n");
      out.write("                                                        <a href=\"product-sticky.html\" class=\"dropdown-item\">Product\n");
      out.write("                                                            Sticky</a>\n");
      out.write("                                                    </li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            <li class=\"nav-item dropdown dropdown-mega\">\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle ps-xl-2 ps-0\"\n");
      out.write("                                                   href=\"javascript:void(0)\" data-bs-toggle=\"dropdown\">Mega\n");
      out.write("                                                    Menu</a>\n");
      out.write("\n");
      out.write("                                                <div class=\"dropdown-menu dropdown-menu-2\">\n");
      out.write("                                                    <div class=\"row\">\n");
      out.write("                                                        <div class=\"dropdown-column col-xl-3\">\n");
      out.write("                                                            <h5 class=\"dropdown-header\">Daily Vegetables</h5>\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Beans & Brinjals</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Broccoli &\n");
      out.write("                                                                Cauliflower</a>\n");
      out.write("\n");
      out.write("                                                            <a href=\"shop-left-sidebar.html\"\n");
      out.write("                                                               class=\"dropdown-item\">Chilies, Garlic</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Vegetables &\n");
      out.write("                                                                Salads</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Gourd, Cucumber</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Herbs & Sprouts</a>\n");
      out.write("\n");
      out.write("                                                            <a href=\"demo-personal-portfolio.html\"\n");
      out.write("                                                               class=\"dropdown-item\">Lettuce & Leafy</a>\n");
      out.write("                                                        </div>\n");
      out.write("\n");
      out.write("                                                        <div class=\"dropdown-column col-xl-3\">\n");
      out.write("                                                            <h5 class=\"dropdown-header\">Baby Tender</h5>\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Beans & Brinjals</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Broccoli &\n");
      out.write("                                                                Cauliflower</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Chilies, Garlic</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Vegetables &\n");
      out.write("                                                                Salads</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Gourd, Cucumber</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Potatoes &\n");
      out.write("                                                                Tomatoes</a>\n");
      out.write("\n");
      out.write("                                                            <a href=\"shop-left-sidebar.html\"\n");
      out.write("                                                               class=\"dropdown-item\">Peas & Corn</a>\n");
      out.write("                                                        </div>\n");
      out.write("\n");
      out.write("                                                        <div class=\"dropdown-column col-xl-3\">\n");
      out.write("                                                            <h5 class=\"dropdown-header\">Exotic Vegetables</h5>\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Asparagus &\n");
      out.write("                                                                Artichokes</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Avocados & Peppers</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Broccoli &\n");
      out.write("                                                                Zucchini</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Celery, Fennel &\n");
      out.write("                                                                Leeks</a>\n");
      out.write("\n");
      out.write("                                                            <a class=\"dropdown-item\"\n");
      out.write("                                                               href=\"shop-left-sidebar.html\">Chilies & Lime</a>\n");
      out.write("                                                        </div>\n");
      out.write("\n");
      out.write("                                                        <div class=\"dropdown-column dropdown-column-img col-3\">\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"rightside-box\">\n");
      out.write("                            <div class=\"search-full\">\n");
      out.write("                                <div class=\"input-group\">\n");
      out.write("                                        <span class=\"input-group-text\">\n");
      out.write("                                            <i data-feather=\"search\" class=\"font-light\"></i>\n");
      out.write("                                        </span>\n");
      out.write("                                    <input type=\"text\" class=\"form-control search-type\" placeholder=\"Search here..\">\n");
      out.write("                                    <span class=\"input-group-text close-search\">\n");
      out.write("                                            <i data-feather=\"x\" class=\"font-light\"></i>\n");
      out.write("                                        </span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <ul class=\"right-side-menu\">\n");
      out.write("                                <li class=\"right-side\">\n");
      out.write("                                    <div class=\"delivery-login-box\">\n");
      out.write("                                        <div class=\"delivery-icon\">\n");
      out.write("                                            <div class=\"search-box\">\n");
      out.write("                                                <i data-feather=\"search\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"right-side\">\n");
      out.write("                                    <a href=\"wishlist.html\" class=\"btn p-0 position-relative header-wishlist\">\n");
      out.write("                                        <i data-feather=\"bookmark\"></i>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"right-side\">\n");
      out.write("                                    <div class=\"onhover-dropdown header-badge\">\n");
      out.write("                                        <button type=\"button\" class=\"btn p-0 position-relative header-wishlist\">\n");
      out.write("                                            <i data-feather=\"shopping-cart\"></i>\n");
      out.write("                                            <span class=\"position-absolute top-0 start-100 translate-middle badge\">2\n");
      out.write("                                                    <span class=\"visually-hidden\">unread messages</span>\n");
      out.write("                                                </span>\n");
      out.write("                                        </button>\n");
      out.write("\n");
      out.write("                                        <div class=\"onhover-div\">\n");
      out.write("                                            <ul class=\"cart-list\">\n");
      out.write("                                                <li class=\"product-box-contain\">\n");
      out.write("                                                    <div class=\"drop-cart\">\n");
      out.write("                                                        <a href=\"product-left-thumbnail.html\" class=\"drop-image\">\n");
      out.write("                                                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/vegetable/product/1.png\"\n");
      out.write("                                                                 class=\"blur-up lazyload\" alt=\"\">\n");
      out.write("                                                        </a>\n");
      out.write("\n");
      out.write("                                                        <div class=\"drop-contain\">\n");
      out.write("                                                            <a href=\"product-left-thumbnail.html\">\n");
      out.write("                                                                <h5>Fantasy Crunchy Choco Chip Cookies</h5>\n");
      out.write("                                                            </a>\n");
      out.write("                                                            <h6><span>1 x</span> $80.58</h6>\n");
      out.write("                                                            <button class=\"close-button close_button\">\n");
      out.write("                                                                <i class=\"fa-solid fa-xmark\"></i>\n");
      out.write("                                                            </button>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </li>\n");
      out.write("\n");
      out.write("                                                <li class=\"product-box-contain\">\n");
      out.write("                                                    <div class=\"drop-cart\">\n");
      out.write("                                                        <a href=\"product-left-thumbnail.html\" class=\"drop-image\">\n");
      out.write("                                                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/vegetable/product/2.png\"\n");
      out.write("                                                                 class=\"blur-up lazyload\" alt=\"\">\n");
      out.write("                                                        </a>\n");
      out.write("\n");
      out.write("                                                        <div class=\"drop-contain\">\n");
      out.write("                                                            <a href=\"product-left-thumbnail.html\">\n");
      out.write("                                                                <h5>Peanut Butter Bite Premium Butter Cookies 600 g\n");
      out.write("                                                                </h5>\n");
      out.write("                                                            </a>\n");
      out.write("                                                            <h6><span>1 x</span> $25.68</h6>\n");
      out.write("                                                            <button class=\"close-button close_button\">\n");
      out.write("                                                                <i class=\"fa-solid fa-xmark\"></i>\n");
      out.write("                                                            </button>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("\n");
      out.write("                                            <div class=\"price-box\">\n");
      out.write("                                                <h5>Total :</h5>\n");
      out.write("                                                <h4 class=\"theme-color fw-bold\">$106.58</h4>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"button-group\">\n");
      out.write("                                                <a href=\"cart.html\" class=\"btn btn-sm cart-button\">View Cart</a>\n");
      out.write("                                                <a href=\"checkout.html\" class=\"btn btn-sm cart-button theme-bg-color\n");
      out.write("                                                    text-white\">Checkout</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"right-side onhover-dropdown\">\n");
      out.write("                                    <div class=\"delivery-login-box\">\n");
      out.write("                                        <div class=\"delivery-icon\">\n");
      out.write("                                            <i data-feather=\"user\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"delivery-detail\">\n");
      out.write("                                            <h6>Hello,</h6>\n");
      out.write("                                            <h5>My Account</h5>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"onhover-div onhover-div-login\">\n");
      out.write("                                        <ul class=\"user-box-name\">\n");
      out.write("                                            <li class=\"product-box-contain\">\n");
      out.write("                                                <i></i>\n");
      out.write("                                                <a href=\"login.html\">Log In</a>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            <li class=\"product-box-contain\">\n");
      out.write("                                                <a href=\"sign-up.html\">Register</a>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            <li class=\"product-box-contain\">\n");
      out.write("                                                <a href=\"forgot.html\">Forgot Password</a>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("<!-- Header End -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- mobile fix menu start -->\n");
      out.write("<div class=\"mobile-menu d-md-none d-block mobile-cart\">\n");
      out.write("    <ul>\n");
      out.write("        <li class=\"active\">\n");
      out.write("            <a href=\"index.html\">\n");
      out.write("                <i class=\"iconly-Home icli\"></i>\n");
      out.write("                <span>Home</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <li class=\"mobile-category\">\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("                <i class=\"iconly-Category icli js-link\"></i>\n");
      out.write("                <span>Category</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <li>\n");
      out.write("            <a href=\"search.html\" class=\"search-box\">\n");
      out.write("                <i class=\"iconly-Search icli\"></i>\n");
      out.write("                <span>Search</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <li>\n");
      out.write("            <a href=\"wishlist.html\" class=\"notifi-wishlist\">\n");
      out.write("                <i class=\"iconly-Heart icli\"></i>\n");
      out.write("                <span>My Wish</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("\n");
      out.write("        <li>\n");
      out.write("            <a href=\"cart.html\">\n");
      out.write("                <i class=\"iconly-Bag-2 icli fly-cate\"></i>\n");
      out.write("                <span>Cart</span>\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("<!-- mobile fix menu end -->\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
